language: php

php:
  - 7.1

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update

install: composer update --prefer-source

script:
  - vendor/bin/phpcs --ignore=/vendor/*,/Tests/Resources/app/* --extensions=php --encoding=utf-8 --standard=PSR2 -np .
  - vendor/bin/phpunit tests --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
